## SET YOUR VALUES IN A COPY OF THIS CALLED config_setup.yaml

# Setup config
FFMPEG_PATH : r"/Users/aa/Documents/Dev/data-video-visualization/ffmpeg" # This should to be to executable file for ffmpeg
DATA_WORKING_DIR : "working_directory" # where data files will be read from, and videos ouput to
