### SET YOUR VALUES IN A COPY OF THIS CALLED config_setup.yaml

## Setup config

# This should to be to executable file for ffmpeg
# NOTE: please use single quotes for the string, otherwise yaml will try to parse backslashes as 
#   escape characters!
FFMPEG_PATH : 'C:\Program Files\GNU Octave\Octave-7.3.0\mingw64\bin\ffmpeg.exe'

# where data files will be read from, and videos ouput to
DATA_WORKING_DIR : "working_directory" 
